terraform {
  required_version = ">= 1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    # Applications, service principals and federated credentials live in the
    # Entra directory and are created through Microsoft Graph, not ARM. This is
    # the only module in the project that needs directory permissions, which is
    # why CI never plans or applies it. See RUNBOOK.md operation 2.
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0"
    }
  }
}

# Both provider configurations are generated by Terragrunt: azurerm by
# root.hcl, azuread by live/shared/identity/terragrunt.hcl.
